Repository zhmcclient/python-zhmcclient, pull requests merged in 2021-08, with the labels that each got.

#817 Fixed Keyrror when accessing se-version in list_permitted_xxx()
  docs/changes.rst
  zhmcclient/_console.py
Labels: priority

#815 Made read/write of properties dict in resource objects thread-safe
  docs/changes.rst
  tests/unit/zhmcclient/test_resource.py
  zhmcclient/_activation_profile.py
  zhmcclient/_adapter.py
  zhmcclient/_capacity_group.py
  zhmcclient/_cpc.py
  zhmcclient/_hba.py
  zhmcclient/_ldap_server_definition.py
  zhmcclient/_lpar.py
  zhmcclient/_nic.py
  zhmcclient/_partition.py
  zhmcclient/_password_rule.py
  zhmcclient/_port.py
  zhmcclient/_resource.py
  zhmcclient/_storage_group.py
  zhmcclient/_storage_group_template.py
  zhmcclient/_storage_volume.py
  zhmcclient/_storage_volume_template.py
  zhmcclient/_user.py
  zhmcclient/_user_pattern.py
  zhmcclient/_user_role.py
  zhmcclient/_virtual_function.py
  zhmcclient/_virtual_storage_resource.py
  zhmcclient/_virtual_switch.py
Labels: review needed

#820 Release 0.32.1
  docs/changes.rst
  zhmcclient/_version.py
Labels: review needed

#828 lpar: Fix body issue with STOP operation
  zhmcclient/_lpar.py
Labels: rollback needed

#831 Added previous Lpar.stop() fix to change log
  docs/changes.rst
Labels: rollback done
