Repository zhmcclient/python-zhmcclient, pull requests merged in 2023-10, with the labels that each got.

#1279 Added support for 'List OS Messages' in DPM+classic mode
  docs/changes.rst
  tests/end2end/test_lpar.py
  tests/end2end/test_partition.py
  zhmcclient/_lpar.py
  zhmcclient/_partition.py
Labels: review needed

#1283 Added Console.list_permitted_adapters()
  tests/end2end/test_adapter.py
  zhmcclient/_console.py
  zhmcclient/_manager.py
Labels: review needed

#1287 Fixed safety issues up to 2023-10-05
  .safety-policy.yml
  dev-requirements.txt
  docs/changes.rst
  minimum-constraints.txt
Labels: rollback done

#1271 Added unit tests and end2end tests for list permitted partitions
  docs/changes.rst
  examples/example_mocked_z16_dpm.yaml
  tests/end2end/test_partition.py
  tests/unit/zhmcclient/test_partition.py
Labels: area: test

#1298 Added testcase descriptions to test_resource.py
  tests/unit/zhmcclient/test_resource.py
Labels: review needed

#1305 Fixed LPAR reset methods; Deprecated deferred status parms in LPAR methods
  docs/changes.rst
  zhmcclient/_lpar.py
  zhmcclient/_utils.py
Labels: review needed

#1315 Resolved dependency conflict with importlib-metadata on Python 3.7
  dev-requirements.txt
  minimum-constraints.txt
Labels: area: develop, type: bug, rollback done

#1313 Shortened status timeout to 60 sec; fixed status_timeout descriptions
  docs/changes.rst
  zhmcclient/_constants.py
  zhmcclient/_lpar.py
  zhmcclient/_partition.py
Labels: review needed

#1314 1.11: Shortened status timeout to 60 sec; fixed status_timeout descriptions
  docs/changes.rst
  zhmcclient/_constants.py
  zhmcclient/_lpar.py
  zhmcclient/_partition.py
Labels: waiting
