Repository zhmcclient/python-zhmcclient, pull requests merged in 2025-03, with the labels that each got.

#1770 Drop storage/network ports for removed adapters
  changes/1764.fix.1.rst
  zhmcclient/_cpc.py
Labels: area: code, review needed

#1742 Added retries when HMC returns busy (HTTP 409)
  changes/noissue.1.fix.rst
  zhmcclient/_partition_link.py
  zhmcclient/_session.py
  zhmcclient_mock/_session.py
Labels: review needed

#1776 Improved performance of LPAR/adapter lookup during metrics; Fixed exception msg
  changes/1775.feature.1.rst
  changes/1775.feature.2.rst
  changes/1775.fix.1.rst
  changes/1775.fix.2.rst
  zhmcclient/_console.py
  zhmcclient/_metrics.py
Labels: review needed

#1693 Dev: Started using the trusted publisher concept of Pypi
  .github/workflows/publish.yml
  changes/1738.feature.rst
Labels: under work, rollback needed

#1781 End2end test: Improved test method 'test_partlink_zzz_cleanup()'
  changes/1749.cleanup.rst
  tests/end2end/test_partition_link.py
Labels: review needed

#1790 Improved repr() of Session objects
  changes/noissue.sessionrepr.feature.rst
  zhmcclient/_session.py
Labels: review needed

#1782 Consolidated different ways to enable logging in end2end tests
  changes/1750.cleanup.rst
  tests/end2end/test_activation_profile.py
  tests/end2end/test_lpar.py
  tests/end2end/test_nic.py
  tests/end2end/test_partition.py
  tests/end2end/utils.py
  zhmcclient/testutils/_hmc_definition_fixtures.py
Labels: review needed

#1791 Improved logging and error reporting for session logon
  changes/noissue.5.feature.rst
  changes/noissue.6.feature.rst
  zhmcclient/_session.py
Labels: review needed
